# Generated by Django 5.2.17 on 2026-09-09 23:25

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PhysiologicalObservation',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('subject_token', models.CharField(db_index=True, max_length=64)),
                ('observed_on', models.DateField(db_index=True)),
                ('observed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('metric_code', models.CharField(db_index=True, max_length=64)),
                ('value', models.FloatField()),
                ('source', models.CharField(default='wearable', max_length=32)),
            ],
            options={
                'db_table': 'physiological_observation',
                'indexes': [models.Index(fields=['subject_token', '-observed_on'], name='physiologic_subject_2b03a4_idx')],
                'constraints': [models.UniqueConstraint(fields=('subject_token', 'observed_on', 'metric_code'), name='uniq_bio_metric_day')],
            },
        ),
    ]
