"""Generator version, recorded in every manifest.

Separate from ``__init__`` so that ``writer.py`` can record it without importing
the package's public surface, which would be a cycle.

This string is part of the output contract. A dataset generated by 0.1.0 and one
generated by 0.2.0 from the same seed are not required to match byte for byte —
determinism is a promise about a seed *within* a version, not across versions —
so a consumer comparing two corpora has to check this field first.
"""

from __future__ import annotations

GENERATOR_VERSION = "0.1.0"
