export type PersonnelLang = "en" | "hi";

const COPY = {
  en: {
    title: "MANOBAL",
    lede: "Your welfare record. A named picture only — never a score.",
    enter: "Continue as personnel",
    today: "Today",
    checkin: "Check-in",
    talk: "Talk",
    more: "More",
    picture: "Your picture",
    why: "Why this picture",
    next: "What to do next",
    engine: "How this picture works",
    streak: "Check-in streak",
    pictureMoved: "Today’s check-in changed the named picture.",
    pictureSame: "Today’s check-in is saved. The named picture is unchanged.",
    consent: "What you share",
    journal: "Journal",
    help: "Need help now",
    helplines: "Show helplines",
    helplineHint: "Numbers appear without opening a welfare record. SOS notifies an officer.",
    sos: "Send SOS",
    holdToTalk: "Hold to talk",
    listening: "Listening… release to send",
    thinking: "Listening on the unit server…",
    send: "Send",
    language: "Language",
    signOut: "Leave this device",
    talkHint: "Hold to speak. Crisis words stay on this phone. A cloud listener replies when configured.",
    checkinHint: "Five 1–5 items. Nothing you type here leaves the device except these numbers.",
    saved: "Saved. This is not a diagnosis.",
  },
  hi: {
    title: "मनोबल",
    lede: "आपका कल्याण रिकॉर्ड। केवल चित्र — कोई अंक नहीं।",
    enter: "कार्मिक के रूप में जारी रखें",
    today: "आज",
    checkin: "जाँच",
    talk: "बात करें",
    more: "और",
    picture: "आपका चित्र",
    why: "यह चित्र क्यों",
    next: "अब क्या करें",
    engine: "यह चित्र कैसे बनता है",
    streak: "लगातार जाँच",
    pictureMoved: "आज की जाँच ने नामित चित्र बदल दिया।",
    pictureSame: "आज की जाँच सहेजी गई। नामित चित्र वही है।",
    consent: "आप क्या साझा करते हैं",
    journal: "जर्नल",
    help: "अभी मदद चाहिए",
    helplines: "हेल्पलाइन दिखाएँ",
    helplineHint: "नंबर बिना रिकॉर्ड बनाए दिखते हैं। एसओएस अधिकारी को सूचित करता है।",
    sos: "एसओएस भेजें",
    holdToTalk: "बात करने के लिए दबाएँ",
    listening: "सुन रहा है… छोड़कर भेजें",
    thinking: "इकाई सर्वर सुन रहा है…",
    send: "भेजें",
    language: "भाषा",
    signOut: "इस उपकरण को छोड़ें",
    talkHint: "बोलने के लिए दबाएँ। संकट शब्द यहीं रहते हैं।",
    checkinHint: "पाँच 1–5 प्रश्न। यहाँ से केवल ये संख्याएँ जाती हैं।",
    saved: "सहेजा गया। यह निदान नहीं है।",
  },
} as const;

export function personnelCopy(lang: PersonnelLang) {
  return COPY[lang];
}
