# Generated by Django 5.2.17 on 2026-09-09 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SpentAssertion',
            fields=[
                ('assertion_id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('spent_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'spent_assertion',
            },
        ),
        migrations.CreateModel(
            name='ResolutionAudit',
            fields=[
                ('seq', models.BigAutoField(primary_key=True, serialize=False)),
                ('occurred_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('direction', models.CharField(choices=[('tokenise', 'Tokenise (ingest boundary, write direction)'), ('resolve', 'Resolve (case path, read direction)'), ('break_glass', 'Break-glass resolve (emergency)')], max_length=16)),
                ('granted', models.BooleanField()),
                ('denial_reason', models.CharField(blank=True, default='', max_length=32)),
                ('actor_id', models.CharField(db_index=True, max_length=64)),
                ('actor_role', models.CharField(max_length=32)),
                ('actor_unit_code', models.CharField(blank=True, default='', max_length=32)),
                ('workload_id', models.CharField(max_length=128)),
                ('subject_token', models.CharField(blank=True, default='', max_length=64)),
                ('case_id', models.CharField(blank=True, default='', max_length=64)),
                ('grant_id', models.CharField(blank=True, default='', max_length=64)),
                ('assertion_id', models.CharField(blank=True, default='', max_length=64)),
                ('purpose_code', models.CharField(blank=True, default='', max_length=64)),
                ('justification', models.TextField(blank=True, default='')),
                ('record_count', models.PositiveIntegerField(default=1)),
                ('anomalies', models.JSONField(default=list)),
                ('source_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('prev_hash', models.CharField(max_length=64)),
                ('entry_hash', models.CharField(max_length=64, unique=True)),
            ],
            options={
                'db_table': 'resolution_audit',
                'indexes': [models.Index(fields=['actor_id', '-occurred_at'], name='res_audit_actor_idx'), models.Index(fields=['direction', '-occurred_at'], name='res_audit_dir_idx')],
            },
        ),
        migrations.CreateModel(
            name='SubjectIdentity',
            fields=[
                ('subject_token', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('service_no_index', models.CharField(db_index=True, max_length=64, unique=True)),
                ('wrapped_key', models.BinaryField()),
                ('key_version', models.PositiveSmallIntegerField()),
                ('service_no_enc', models.BinaryField()),
                ('full_name_enc', models.BinaryField()),
                ('rank_code_enc', models.BinaryField()),
                ('mobile_e164_enc', models.BinaryField()),
                ('current_unit_code', models.CharField(db_index=True, max_length=32)),
                ('current_unit_path', models.CharField(max_length=512)),
                ('force_code', models.CharField(db_index=True, max_length=16)),
                ('enrolled_on', models.DateField()),
                ('separated_on', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'subject identities',
                'db_table': 'subject_identity',
                'indexes': [models.Index(fields=['separated_on'], name='subj_ident_separated_idx')],
            },
        ),
    ]
