# Generated by Django 5.2.17 on 2026-09-09 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DutyObservation',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('subject_token', models.CharField(db_index=True, max_length=64)),
                ('observed_on', models.DateField(db_index=True)),
                ('duty_hours', models.FloatField(blank=True, null=True)),
                ('duty_hours_7d', models.FloatField(blank=True, null=True)),
                ('night_duty', models.BooleanField(default=False)),
                ('consecutive_duty_days', models.PositiveSmallIntegerField(default=0)),
                ('high_alert_posting', models.BooleanField(default=False)),
                ('location_changes_30d', models.PositiveSmallIntegerField(default=0)),
                ('source_batch_id', models.BigIntegerField(blank=True, null=True)),
                ('ingested_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'duty_observation',
                'indexes': [models.Index(fields=['subject_token', '-observed_on'], name='duty_observ_subject_bb1865_idx')],
                'constraints': [models.UniqueConstraint(fields=('subject_token', 'observed_on'), name='uniq_duty_observation_day')],
            },
        ),
        migrations.CreateModel(
            name='EngagementObservation',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('subject_token', models.CharField(db_index=True, max_length=64)),
                ('observed_on', models.DateField(db_index=True)),
                ('checkin_completed', models.BooleanField(default=False)),
                ('app_sessions', models.PositiveSmallIntegerField(default=0)),
                ('median_response_seconds', models.FloatField(blank=True, null=True)),
                ('days_since_last_interaction', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('resource_views', models.PositiveSmallIntegerField(default=0)),
                ('ingested_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'engagement_observation',
                'indexes': [models.Index(fields=['subject_token', '-observed_on'], name='engagement__subject_863401_idx')],
                'constraints': [models.UniqueConstraint(fields=('subject_token', 'observed_on'), name='uniq_engagement_observation_day')],
            },
        ),
        migrations.CreateModel(
            name='LeaveObservation',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('subject_token', models.CharField(db_index=True, max_length=64)),
                ('observed_on', models.DateField(db_index=True)),
                ('days_since_last_leave', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('leave_denied_count_90d', models.PositiveSmallIntegerField(default=0)),
                ('leave_deferred_days', models.PositiveSmallIntegerField(default=0)),
                ('pending_leave_application', models.BooleanField(default=False)),
                ('home_distance_band', models.CharField(blank=True, default='', max_length=16)),
                ('source_batch_id', models.BigIntegerField(blank=True, null=True)),
                ('ingested_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'leave_observation',
                'indexes': [models.Index(fields=['subject_token', '-observed_on'], name='leave_obser_subject_384fbc_idx')],
                'constraints': [models.UniqueConstraint(fields=('subject_token', 'observed_on'), name='uniq_leave_observation_day')],
            },
        ),
    ]
