# Generated by Django 5.2.17 on 2026-09-09 20:51

import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AcuteSignal',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('subject_token', models.CharField(db_index=True, max_length=64)),
                ('detected_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('signal_code', models.CharField(max_length=48)),
                ('source', models.CharField(choices=[('instrument', 'Instrument item'), ('device_triage', 'On-device crisis triage'), ('self_report', 'Direct request for help'), ('officer', 'Officer-raised concern')], max_length=24)),
                ('self_initiated', models.BooleanField(default=False)),
                ('dispatched_at', models.DateTimeField(blank=True, null=True)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('wdec_reviewed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'acute_signal',
                'ordering': ('-detected_at',),
                'indexes': [models.Index(fields=['acknowledged_at', 'detected_at'], name='acute_signa_acknowl_3512e0_idx')],
            },
        ),
        migrations.CreateModel(
            name='CheckinResponse',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('subject_token', models.CharField(db_index=True, max_length=64)),
                ('observed_on', models.DateField(db_index=True)),
                ('submitted_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('mood', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('sleep_quality', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('stress', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('connection', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('concern_tag', models.CharField(blank=True, default='', max_length=32)),
            ],
            options={
                'db_table': 'checkin_response',
                'indexes': [models.Index(fields=['subject_token', '-observed_on'], name='checkin_res_subject_e4d018_idx')],
                'constraints': [models.UniqueConstraint(fields=('subject_token', 'observed_on'), name='uniq_checkin_day')],
            },
        ),
        migrations.CreateModel(
            name='InstrumentResponse',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('subject_token', models.CharField(db_index=True, max_length=64)),
                ('instrument_code', models.CharField(db_index=True, max_length=32)),
                ('instrument_version', models.CharField(max_length=16)),
                ('language_code', models.CharField(default='en', max_length=8)),
                ('completed_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('total_score', models.FloatField()),
                ('subscales', models.JSONField(blank=True, default=dict)),
                ('duration_seconds', models.PositiveIntegerField(blank=True, null=True)),
                ('straight_lined', models.BooleanField(default=False)),
                ('is_acute_flagged', models.BooleanField(db_index=True, default=False)),
                ('acute_item_code', models.CharField(blank=True, default='', max_length=32)),
            ],
            options={
                'db_table': 'instrument_response',
                'ordering': ('-completed_at',),
                'indexes': [models.Index(fields=['subject_token', 'instrument_code', '-completed_at'], name='instrument__subject_ac42fa_idx'), models.Index(fields=['is_acute_flagged', '-completed_at'], name='instrument__is_acut_af7871_idx')],
            },
        ),
        migrations.CreateModel(
            name='JournalEntry',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('subject_token', models.CharField(db_index=True, max_length=64)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('ciphertext', models.BinaryField()),
                ('key_id', models.CharField(max_length=64)),
                ('nonce', models.BinaryField()),
                ('crisis_referred_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'journal_entry',
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['subject_token', '-created_at'], name='journal_ent_subject_0ab424_idx')],
            },
        ),
    ]
