# Generated by Django 5.2.17 on 2026-09-09 23:25

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psystore', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentSession',
            fields=[
                ('session_id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('subject_token', models.CharField(db_index=True, max_length=64)),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_turn_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('turn_count', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'db_table': 'agent_session',
                'indexes': [models.Index(fields=['subject_token', '-last_turn_at'], name='agent_sessi_subject_068e81_idx')],
            },
        ),
    ]
