# Generated by Django 5.2.17 on 2026-09-09 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('governance', '0002_append_only_guards'),
    ]

    operations = [
        migrations.AddField(
            model_name='consententry',
            name='consent_text_sha256',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
    ]
