# Generated by Django 5.2.17 on 2026-09-09 23:25

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('governance', '0004_governance_guards'),
    ]

    operations = [
        migrations.CreateModel(
            name='RulesetProposal',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('version', models.CharField(max_length=32)),
                ('digest', models.CharField(max_length=64)),
                ('signature', models.TextField()),
                ('signing_key_id', models.CharField(max_length=64)),
                ('artefact_path', models.CharField(blank=True, default='', max_length=512)),
                ('shadow_report', models.JSONField(blank=True, default=dict)),
                ('proposed_by', models.CharField(max_length=128)),
                ('proposed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('clinical_approver', models.CharField(blank=True, default='', max_length=128)),
                ('clinical_at', models.DateTimeField(blank=True, null=True)),
                ('wdec_approver', models.CharField(blank=True, default='', max_length=128)),
                ('wdec_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending dual approval'), ('rejected', 'Rejected'), ('registered', 'Registered as a RulesetVersion')], default='pending', max_length=16)),
            ],
            options={
                'db_table': 'ruleset_proposal',
                'ordering': ('-proposed_at',),
            },
        ),
    ]
