# Generated by Django 5.2.17 on 2026-09-09 23:25

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VoiceObservation',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('subject_token', models.CharField(db_index=True, max_length=64)),
                ('captured_on', models.DateField(db_index=True)),
                ('captured_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('features', models.JSONField(blank=True, default=dict)),
                ('embedding', models.JSONField(blank=True, default=list)),
                ('language_code', models.CharField(default='en', max_length=8)),
            ],
            options={
                'db_table': 'voice_observation',
                'indexes': [models.Index(fields=['subject_token', '-captured_on'], name='voice_obser_subject_840a99_idx')],
                'constraints': [models.UniqueConstraint(fields=('subject_token', 'captured_on'), name='uniq_voice_checkin_day')],
            },
        ),
    ]
